package nl.salah.civicsignal.security;
import com.fasterxml.jackson.databind.ObjectMapper;import io.micrometer.core.instrument.MeterRegistry;import jakarta.servlet.http.HttpServletResponse;import java.time.Clock;import java.util.Map;import org.springframework.context.annotation.*;import org.springframework.http.*;import org.springframework.security.config.annotation.web.builders.HttpSecurity;import org.springframework.security.config.http.SessionCreationPolicy;import org.springframework.security.core.userdetails.*;import org.springframework.security.crypto.bcrypt.BCryptPasswordEncoder;import org.springframework.security.crypto.password.PasswordEncoder;import org.springframework.security.web.SecurityFilterChain;import org.springframework.security.web.authentication.www.BasicAuthenticationFilter;
@Configuration public class SecurityConfiguration {
 @Bean PasswordEncoder passwordEncoder(){return new BCryptPasswordEncoder();}
 @Bean UserDetailsService users(AdminSecurityProperties p,PasswordEncoder e){return username->{if(!p.configured()||!p.username().equals(username))throw new UsernameNotFoundException("disabled");return User.withUsername(p.username()).password(e.encode(p.password())).roles("ADMIN").build();};}
 @Bean Clock securityClock(){return Clock.systemUTC();}
 @Bean AdminAuthRateLimitFilter rateLimit(Clock c,ObjectMapper j,MeterRegistry m){return new AdminAuthRateLimitFilter(c,j,m);}
 @Bean SecurityFilterChain security(HttpSecurity h,ObjectMapper json,MeterRegistry metrics,AdminAuthRateLimitFilter limiter)throws Exception{h.csrf(c->c.disable()).sessionManagement(s->s.sessionCreationPolicy(SessionCreationPolicy.STATELESS)).httpBasic(b->b.authenticationEntryPoint((r,x,e)->error(x,json,401,"UNAUTHORIZED","Niet geautoriseerd."))).authorizeHttpRequests(a->a.requestMatchers(HttpMethod.OPTIONS,"/**").permitAll().requestMatchers("/api/v1/status","/actuator/health","/actuator/info","/api/v1/report-events","/api/v1/reports/search","/api/v1/reports/map","/api/v1/analytics/summary").permitAll().requestMatchers("/api/v1/admin/**","/actuator/**").hasRole("ADMIN").anyRequest().denyAll()).exceptionHandling(e->e.accessDeniedHandler((r,x,z)->{metrics.counter("civic_admin_access_denied_total").increment();error(x,json,403,"FORBIDDEN","Toegang geweigerd.");})).addFilterBefore(limiter,BasicAuthenticationFilter.class).headers(x->x.frameOptions(f->f.deny()).contentTypeOptions(c->{}).referrerPolicy(r->r.policy(org.springframework.security.web.header.writers.ReferrerPolicyHeaderWriter.ReferrerPolicy.NO_REFERRER)));return h.build();}
 private void error(HttpServletResponse r,ObjectMapper j,int s,String c,String m)throws java.io.IOException{r.setStatus(s);r.setHeader(HttpHeaders.WWW_AUTHENTICATE,"Basic realm=\"CivicSignal Admin\"");r.setHeader(HttpHeaders.CACHE_CONTROL,"no-store");r.setContentType(MediaType.APPLICATION_JSON_VALUE);j.writeValue(r.getOutputStream(),Map.of("code",c,"message",m));}
}
