import { afterEach, expect, it, vi } from 'vitest'
import { configureAdminClient, getAnalytics, getGeneratorStatus, getReportMap, searchReports } from '../src/api'
import { emptyFilters } from '../src/App'

afterEach(() => { vi.restoreAllMocks(); configureAdminClient(null, () => {}) })
const json = (body: unknown) => new Response(JSON.stringify(body), { status: 200, headers: { 'Content-Type': 'application/json' } })
it('stuurt nooit Authorization met publieke analytics, map of search', async () => { configureAdminClient('Basic placeholder', () => {}); const fetch = vi.spyOn(window, 'fetch').mockImplementation(async () => json({})); await getAnalytics(emptyFilters, 'DAY'); await getReportMap(emptyFilters, '3,50,7,54', 7, 100); await searchReports(emptyFilters); for (const [, init] of fetch.mock.calls.slice(0, 3)) expect(new Headers(init?.headers).has('Authorization')).toBe(false); await getGeneratorStatus(); expect(new Headers(fetch.mock.calls.at(-1)?.[1]?.headers).has('Authorization')).toBe(true) })
it('serialiseert filters, bbox, zoom en limiet centraal', async () => { const fetch = vi.spyOn(window, 'fetch').mockResolvedValue(json({ mode: 'POINTS', points: [], clusters: [], totalMatching: 0, truncated: false })); await getReportMap({ ...emptyFilters, municipality: ' Amsterdam ' }, '4.7,52.2,5.1,52.5', 14, 250); const url = new URL(String(fetch.mock.calls[0][0])); expect(url.searchParams.get('municipality')).toBe('Amsterdam'); expect(url.searchParams.get('bbox')).toBe('4.7,52.2,5.1,52.5'); expect(url.searchParams.get('zoom')).toBe('14'); expect(url.searchParams.get('limit')).toBe('250') })
it('behoudt een exact report-ID als q in de zoekaanvraag', async () => { const fetch = vi.spyOn(window, 'fetch').mockResolvedValue(json({ items: [], totalElements: 0 })); await searchReports({ ...emptyFilters, q: 'AMS-123' }, 0, 20); const url = new URL(String(fetch.mock.calls[0][0])); expect(url.searchParams.get('q')).toBe('AMS-123') })
it('verwerkt ontbrekende optionele velden defensief', async () => { vi.spyOn(window, 'fetch').mockResolvedValue(json({ items: [{ reportId: 'SAFE-1' }, null, {}], totalElements: 1 })); const response = await searchReports(emptyFilters); expect(response.items).toHaveLength(1); expect(response.items[0].location).toBeNull(); expect(response.page).toBe(0) })
