import { render, screen, waitFor } from '@testing-library/react'
import userEvent from '@testing-library/user-event'
import { beforeEach, describe, expect, it, vi } from 'vitest'
import App from '../src/App'
import { AdminAuthProvider } from '../src/AdminAuth'

vi.mock('../src/ChartsPanel', () => ({ default: () => <div><h3>Meldingen door de tijd</h3><h3>Meldingen per categorie</h3><h3>Meldingen per bron</h3><h3>Topgemeenten of stadsdelen</h3><h3>Statusverdeling</h3></div> }))
vi.mock('../src/MapPage', () => ({ MapPage: () => <div>Interactieve kaartmodule</div> }))
const json = (body: unknown, status = 200) => new Response(JSON.stringify(body), { status, headers: { 'Content-Type': 'application/json' } })
const summary = { total: 20, open: 8, closed: 12, withLocation: 18, averageResolutionDays: null, p50ResolutionDays: 0, earliest: '2026-09-01T12:00:00Z', latest: '2026-09-20T12:00:00Z', topCategories: [{ value: 'Afval', count: 8 }], topSources: [{ value: 'OFFICIAL_OPEN_DATA', count: 15 }], topMunicipalities: [{ value: 'Amsterdam', count: 18 }], topDistricts: [{ value: 'West', count: 10 }], topStatuses: [{ value: 'CLOSED', count: 12 }], interval: 'DAY', timeline: [{ timestamp: '2026-09-01T00:00:00Z', count: 1 }] }
const emptySearch = { items: [], page: 0, size: 20, totalElements: 0, totalPages: 0 }
const renderApp = () => render(<AdminAuthProvider><App/></AdminAuthProvider>)

describe('dashboardstate en navigatie', () => {
  beforeEach(() => { vi.restoreAllMocks(); window.history.replaceState({}, '', '/'); Object.defineProperty(navigator, 'clipboard', { configurable: true, value: { writeText: vi.fn().mockResolvedValue(undefined) } }) })
  it('herstelt sectie en filters uit URL en ondersteunt history-state', async () => { window.history.replaceState({}, '', '/reports?sourceType=SYNTHETIC&municipality=Utrecht&page=2'); mockApi(); renderApp(); expect(screen.getByRole('button', { name: 'Meldingen' })).toHaveAttribute('aria-current', 'page'); expect(screen.getByLabelText('Bron')).toHaveValue('SYNTHETIC'); expect(screen.getByLabelText('Gemeente')).toHaveValue('Utrecht'); await userEvent.click(screen.getByRole('button', { name: 'Architectuur' })); expect(location.pathname).toBe('/architecture'); window.history.pushState({}, '', '/reports?municipality=Utrecht'); window.dispatchEvent(new PopStateEvent('popstate')); await waitFor(() => expect(screen.getByRole('button', { name: 'Meldingen' })).toHaveAttribute('aria-current', 'page')) })
  it('houdt draft los van toegepast, maakt chips en wist filters', async () => { const fetch = mockApi(); renderApp(); expect((await screen.findAllByText('20')).length).toBeGreaterThan(0); const before = analyticsCalls(fetch); await userEvent.type(screen.getByLabelText('Gemeente'), '  Amsterdam  '); expect(analyticsCalls(fetch)).toBe(before); await userEvent.click(screen.getByRole('button', { name: 'Filters toepassen' })); await waitFor(() => expect(analyticsCalls(fetch)).toBe(before + 1)); expect(location.search).toContain('municipality=Amsterdam'); expect(screen.getByRole('button', { name: 'Verwijder filter Amsterdam' })).toBeInTheDocument(); await userEvent.click(screen.getByRole('button', { name: 'Wis filters' })); expect(location.search).toBe('') })
  it('valideert datumvolgorde zonder request', async () => { const fetch = mockApi(); renderApp(); expect((await screen.findAllByText('20')).length).toBeGreaterThan(0); const before = analyticsCalls(fetch); await userEvent.type(screen.getByLabelText('Datum vanaf'), '2026-09-10'); await userEvent.type(screen.getByLabelText('Datum tot'), '2026-09-01'); await userEvent.click(screen.getByRole('button', { name: 'Filters toepassen' })); expect(await screen.findByRole('alert')).toHaveTextContent('begindatum'); expect(analyticsCalls(fetch)).toBe(before) })
  it('deelt de veilige volledige URL met groene bevestiging', async () => { mockApi(); renderApp(); await userEvent.click(screen.getByRole('button', { name: 'Deel weergave' })); expect(navigator.clipboard.writeText).toHaveBeenCalledWith(location.href); expect(await screen.findByRole('status')).toHaveTextContent('gekopieerd') })
  it('valt voor delen terug op document copy wanneer Clipboard API ontbreekt', async () => { Object.defineProperty(navigator, 'clipboard', { configurable: true, value: undefined }); const copy = vi.fn().mockReturnValue(true); Object.defineProperty(document, 'execCommand', { configurable: true, value: copy }); mockApi(); renderApp(); await userEvent.click(screen.getByRole('button', { name: 'Deel weergave' })); expect(copy).toHaveBeenCalledWith('copy'); expect(await screen.findByRole('status')).toHaveTextContent('gekopieerd') })
  it('toont nul apart van null en isoleert analyticsfout met retry', async () => { let attempts = 0; vi.spyOn(window, 'fetch').mockImplementation(async input => { if (String(input).includes('/analytics/')) { attempts++; return attempts === 1 ? json({}, 503) : json(summary) } return json(emptySearch) }); renderApp(); expect(await screen.findByText('Overzicht niet beschikbaar')).toBeInTheDocument(); await userEvent.click(screen.getByRole('button', { name: 'Opnieuw proberen' })); expect((await screen.findAllByText('20')).length).toBeGreaterThan(0); expect(screen.getAllByText('Niet beschikbaar').length).toBeGreaterThan(0); expect(screen.getByText('0 dagen')).toBeInTheDocument(); expect(screen.getByText('90%')).toBeInTheDocument() })
  it('mount geen adminpanelen voor login en wel erna', async () => { const fetch = mockApi(); renderApp(); await userEvent.click(screen.getByRole('button', { name: 'Beheer' })); expect(fetch.mock.calls.some(([url]) => String(url).includes('/api/v1/admin/'))).toBe(false); await userEvent.type(screen.getByLabelText('Wachtwoord'), String.fromCharCode(120).repeat(12)); await userEvent.click(screen.getByRole('button', { name: 'Inloggen als beheerder' })); await waitFor(() => expect(fetch.mock.calls.some(([url]) => String(url).includes('/generator/status'))).toBe(true)) })
})

function analyticsCalls(mock: { mock: { calls: unknown[][] } }) { return mock.mock.calls.filter(([url]) => String(url).includes('/analytics/')).length }
function mockApi() { return vi.spyOn(window, 'fetch').mockImplementation(async (input, init) => { const url = String(input); if (url.includes('/analytics/')) return json(summary); if (url.includes('/reports/search')) return json(emptySearch); if (url.includes('/admin/auth/me')) return init?.headers instanceof Headers && init.headers.has('Authorization') ? json({ authenticated: true, username: 'admin', roles: ['ADMIN'], authenticationType: 'BASIC' }) : json({}, 401); if (url.includes('/dead-letters')) return json({ items: [], page: 0, size: 20, totalElements: 0, totalPages: 0 }); if (url.includes('/generator/status')) return json({ enabledByConfiguration: false, running: false, generatedThisRun: 0, maximumPerRun: 100, interval: 'PT15S', duplicateProbability: .1, invalidEventProbability: 0, lastGeneratedAt: null }); if (url.includes('/sources/amsterdam/status')) return json({ enabled: false, sourceName: 'Amsterdam', pageSize: 10, maximumRecordsPerImport: 10, importRunning: false, apiKeyConfigured: false }); if (url.endsWith('/scheduler')) return json({ configuredEnabled: false, active: false, runtimePaused: false, automaticallyPaused: false, currentImportRunning: false, fixedDelay: 'PT15M', failureBackoff: 'PT30M', importLimit: 10, consecutiveFailures: 0, maximumConsecutiveFailures: 5, lastOutcome: 'NEVER_RUN', skippedBecauseLocked: 0 }); if (url.includes('/runs')) return json({ items: [], page: 0, size: 10, totalElements: 0, totalPages: 0 }); return json({}) }) }
