import { render, screen, waitFor } from '@testing-library/react'
import userEvent from '@testing-library/user-event'
import { beforeEach, expect, it, vi } from 'vitest'
import { MapPage } from '../src/MapPage'
import { emptyFilters } from '../src/App'
import { getReportMap } from '../src/api'

vi.mock('../src/api', async original => ({ ...await original<typeof import('../src/api')>(), getReportMap: vi.fn() }))
vi.mock('../src/MapView', () => ({ default: ({ data, onViewport }: { data: { points: { reportId: string }[] } | null; onViewport: (bbox: string, zoom: number) => void }) => <div><button onClick={() => onViewport('4.8,52.3,5,52.5', 14)}>Beweeg mockkaart</button>{data?.points.map(point => <span key={point.reportId}>{point.reportId}</span>)}</div> }))
const map = vi.mocked(getReportMap)
beforeEach(() => map.mockReset())
it('vraagt bbox en zoom pas opnieuw na kaartgebiedknop', async () => { map.mockResolvedValue({ mode: 'CLUSTERS', clusters: [{ key: '0/0/0', location: { lat: 52.3, lon: 4.9 }, count: 18 }], points: [], totalMatching: 18, truncated: false }); render(<MapPage filters={emptyFilters} focus={null}/>); await screen.findByText('18 meldingen'); expect(map).toHaveBeenCalledTimes(1); await userEvent.click(screen.getByRole('button', { name: 'Beweeg mockkaart' })); expect(map).toHaveBeenCalledTimes(1); await userEvent.click(screen.getByRole('button', { name: 'Zoek in dit kaartgebied' })); await waitFor(() => expect(map).toHaveBeenCalledTimes(2)); expect(map.mock.calls[1].slice(1, 4)).toEqual(['4.8,52.3,5,52.5', 14, 500]) })
it('toont puntenlijst, privacy, truncated en annuleert achterhaalde request', async () => { map.mockResolvedValue({ mode: 'POINTS', clusters: [], points: [{ reportId: 'AMS-1', category: 'Afval', municipality: 'Amsterdam', district: 'West', reportStatus: 'OPEN', occurredAt: '2026-09-01T00:00:00Z', sourceType: 'OFFICIAL_OPEN_DATA', location: { lat: 52.37, lon: 4.89 } }], totalMatching: 2, truncated: true }); const view = render(<MapPage filters={emptyFilters} focus={null}/>); expect((await screen.findAllByText('AMS-1')).length).toBeGreaterThan(0); expect(screen.getByText(/Niet alle 2 resultaten/)).toBeInTheDocument(); expect(screen.getByText(/Locaties zijn openbare/)).toBeInTheDocument(); const firstSignal = map.mock.calls[0][4]!; view.rerender(<MapPage filters={{ ...emptyFilters, category: 'Afval' }} focus={null}/>); expect(firstSignal.aborted).toBe(true) })
it('isoleert een kaartfout en kan herproberen', async () => { map.mockRejectedValueOnce(new Error('offline')).mockResolvedValueOnce({ mode: 'POINTS', clusters: [], points: [], totalMatching: 0, truncated: false }); render(<MapPage filters={emptyFilters} focus={null}/>); expect(await screen.findByRole('alert')).toHaveTextContent('tijdelijk'); await userEvent.click(screen.getByRole('button', { name: 'Opnieuw proberen' })); await waitFor(() => expect(map).toHaveBeenCalledTimes(2)); expect(await screen.findByText(/Geen meldingen met een kaartlocatie/)).toBeInTheDocument() })
