import { useEffect, useState } from 'react'
import { AmsterdamSourcePanel } from './AmsterdamSourcePanel'
import { useAdmin } from './AdminAuth'
import { AdminLogin } from './AdminLogin'
import { generatorAction, getDeadLetters, getGeneratorStatus } from './api'
import { SchedulerPanel } from './SchedulerPanel'
import type { DeadLetterResponse, GeneratorStatus } from './types'

const date = (value?: string | null) => value ? new Intl.DateTimeFormat('nl-NL', { dateStyle: 'medium', timeStyle: 'short' }).format(new Date(value)) : 'Niet beschikbaar'

export function AdminPage({ viewOfficial }: { viewOfficial: () => void }) { const { authorization } = useAdmin(); return <section aria-labelledby="admin-title"><p className="eyebrow">Afgeschermd</p><h2 id="admin-title">Beheer</h2><AdminLogin/>{authorization && <><GeneratorPanel/><AmsterdamSourcePanel viewOfficial={viewOfficial}/><SchedulerPanel/><DeadLetters/></>}</section> }

function GeneratorPanel() { const [status, setStatus] = useState<GeneratorStatus | null>(null); const [error, setError] = useState(''); const [busy, setBusy] = useState(false); const load = async () => { setError(''); try { setStatus(await getGeneratorStatus()) } catch { setError('Generatorstatus is tijdelijk niet beschikbaar.') } }; useEffect(() => { void load() }, []); const action = async (name: 'start' | 'stop' | 'generate-one') => { setBusy(true); setError(''); try { const result = await generatorAction(name); if ('running' in result) setStatus(result); else await load() } catch { setError('Generatoractie is niet beschikbaar.') } finally { setBusy(false) } }; return <section className="panel"><div className="section-heading"><div><h3>Synthetische generator</h3><p className="synthetic-warning">Uitsluitend demonstratiedata; nooit officiële meldingen.</p></div><button className="secondary" onClick={() => void load()}>Vernieuwen</button></div>{error && <p className="alert error" role="alert">{error}</p>}{status && <><p>Status: {status.running ? 'actief' : 'gestopt'} · {status.generatedThisRun}/{status.maximumPerRun} · interval {status.interval} · laatste generatie {date(status.lastGeneratedAt)}</p><div className="actions"><button disabled={!status.enabledByConfiguration || busy} onClick={() => void action('start')}>Starten</button><button disabled={!status.enabledByConfiguration || busy} onClick={() => void action('stop')}>Stoppen</button><button disabled={!status.enabledByConfiguration || busy} onClick={() => void action('generate-one')}>Eén melding genereren</button></div>{!status.enabledByConfiguration && <p className="empty">Generator is uitgeschakeld via configuratie.</p>}</>}</section> }

function DeadLetters() { const empty: DeadLetterResponse = { items: [], page: 0, size: 20, totalElements: 0, totalPages: 0 }; const [data, setData] = useState(empty); const [loading, setLoading] = useState(true); const [error, setError] = useState(''); const load = async () => { setLoading(true); setError(''); try { setData(await getDeadLetters()) } catch { setError('Niet-verwerkte meldingen zijn tijdelijk niet beschikbaar.') } finally { setLoading(false) } }; useEffect(() => { void load() }, []); return <section className="panel"><div className="section-heading"><div><h3>Dead-letter queue</h3><p>Begrensde lokale inspectie, zonder automatische polling of replay.</p></div><button className="secondary" onClick={() => void load()}>Vernieuwen</button></div>{loading ? <p>Laden…</p> : error ? <p className="alert error">{error}</p> : data.items.length === 0 ? <p className="empty">Geen niet-verwerkte meldingen.</p> : <div className="dead-letter-list">{data.items.map(item => <article key={`${item.originalTopic}-${item.originalPartition}-${item.originalOffset}`}><h3>{item.failureType}</h3><p>{item.failureMessage.slice(0, 180)}</p><small>{date(item.failedAt)} · key/reportId: {item.originalKey || 'Onbekend'}</small></article>)}</div>}</section> }
