import { useEffect, useState } from 'react'
import { getAmsterdamStatus, importAmsterdam } from './api'
import type { AmsterdamImportResult, AmsterdamStatus } from './types'

export function AmsterdamSourcePanel({ viewOfficial }: { viewOfficial: () => void }) {
 const [status,setStatus]=useState<AmsterdamStatus|null>(null);const [limit,setLimit]=useState(1);const [preview,setPreview]=useState<AmsterdamImportResult|null>(null);const [confirm,setConfirm]=useState(false);const [busy,setBusy]=useState(false);const [message,setMessage]=useState('')
 const refresh=async()=>{try{setStatus(await getAmsterdamStatus())}catch{setMessage('Bronstatus is tijdelijk niet beschikbaar.')}};useEffect(()=>{void refresh()},[])
 const run=async(dryRun:boolean)=>{setBusy(true);setMessage('');try{const r=await importAmsterdam(limit,dryRun);if(dryRun){setPreview(r);setConfirm(false);setMessage('Veilige preview voltooid: er is niets naar Kafka gepubliceerd.')}else setMessage(`Import voltooid: ${r.published} gepubliceerd, ${r.skipped} overgeslagen.`)}catch{setMessage('Import kon niet worden uitgevoerd.')}finally{setBusy(false)}}
 const enabled=!!status?.enabled;const max=status?.maximumRecordsPerImport??100
 return <section className="panel"><h2>Amsterdam Open Data</h2><p><strong>Officiële open data</strong> · Gemeente Amsterdam · Meldingen over de Openbare Ruimte in Amsterdam.</p><p>Openbare subset; niet alle meldingen zijn opgenomen. Creative Commons Naamsvermelding. Persoonsgegevens worden bewust niet geïmporteerd.</p><a href="https://api.data.amsterdam.nl/v1/docs/datasets/meldingen.html" target="_blank" rel="noreferrer">Officiële datasetdocumentatie</a><button className="secondary" onClick={()=>void refresh()}>Status vernieuwen</button>{!status?<p>Bronstatus laden…</p>:<p>Ingeschakeld: {String(status.enabled)} · bron: {status.sourceName} · pagina: {status.pageSize} · maximum: {max} · API-key geconfigureerd: {String(status.apiKeyConfigured)}</p>}<label>Importlimiet<input aria-label="Amsterdam importlimiet" type="number" min="1" max={Math.min(100,max)} value={limit} onChange={e=>{setLimit(Math.max(1,Math.min(Number(e.target.value),Math.min(100,max))));setConfirm(false)}} /></label><button disabled={!enabled||busy} onClick={()=>void run(true)}>Veilige preview uitvoeren</button>{preview&&<div aria-live="polite"><p>Preview: fetched {preview.fetched}, valid {preview.fetched-preview.skipped}, skipped {preview.skipped}, failed {preview.failed}.</p>{preview.previewItems?.map(i=><p key={i.reportId}>{i.reportId} · {i.category} · {i.district}</p>)}<p>Je staat op het punt maximaal {limit} officiële openbare records naar Kafka te publiceren.</p><label><input type="checkbox" checked={confirm} onChange={e=>setConfirm(e.target.checked)}/> Ik begrijp dat deze records naar de lokale Kafka-keten worden gepubliceerd.</label><button disabled={!confirm||busy||!enabled} onClick={()=>void run(false)}>Publiceer naar Kafka</button></div>}{message&&<p aria-live="polite" className="alert">{message}</p>}<button disabled={!preview} onClick={viewOfficial}>Bekijk officiële meldingen</button><p><small>API-keyconfiguratie gebeurt alleen via `CIVICSIGNAL_AMSTERDAM_API_KEY` op de backend.</small></p></section>
}
