import { FormEvent, useEffect, useState } from 'react'
import { generatorAction, getDeadLetters, getGeneratorStatus, publishReport, searchReports } from './api'
import type { DeadLetterResponse, GeneratorStatus, SearchResponse } from './types'

const empty: SearchResponse = { items: [], page: 0, size: 20, totalElements: 0, totalPages: 0 }
const noDlt: DeadLetterResponse = { items: [], page: 0, size: 20, totalElements: 0, totalPages: 0 }
const categories = ['Wegen', 'Verlichting', 'Afval', 'Groen', 'Water', 'Overlast', 'Verkeer', 'Overig']
const date = (value?: string | null) => value ? new Intl.DateTimeFormat('nl-NL', { dateStyle: 'medium', timeStyle: 'short' }).format(new Date(value)) : '—'

export default function App() {
  const initial = new URLSearchParams(window.location.search)
  const [filters, setFilters] = useState({ q: initial.get('q') ?? '', category: initial.get('category') ?? '', district: initial.get('district') ?? '', sourceType: initial.get('sourceType') ?? '' })
  const [results, setResults] = useState<SearchResponse>(empty); const [searchError, setSearchError] = useState(''); const [loading, setLoading] = useState(false)
  const [form, setForm] = useState({ reportId: '', category: '', district: '' }); const [formError, setFormError] = useState('')
  const [dlt, setDlt] = useState<DeadLetterResponse>(noDlt); const [dltError, setDltError] = useState(''); const [dltLoading, setDltLoading] = useState(false)
  const [generator, setGenerator] = useState<GeneratorStatus | null>(null); const [generatorError, setGeneratorError] = useState(''); const [generatorLoading, setGeneratorLoading] = useState(false)
  const search = async (next = filters) => { const p = new URLSearchParams(); Object.entries(next).forEach(([key, value]) => { if (value.trim()) p.set(key, value.trim()) }); p.set('page', '0'); p.set('size', '20'); window.history.replaceState({}, '', `?${p}`); setLoading(true); setSearchError(''); try { setResults(await searchReports(p)) } catch { setSearchError('De zoekfunctie is tijdelijk niet beschikbaar.') } finally { setLoading(false) } }
  const loadDlt = async () => { setDltLoading(true); setDltError(''); try { setDlt(await getDeadLetters()) } catch { setDltError('Niet-verwerkte meldingen zijn tijdelijk niet beschikbaar.') } finally { setDltLoading(false) } }
  const loadGenerator = async () => { setGeneratorError(''); try { setGenerator(await getGeneratorStatus()) } catch { setGeneratorError('Generatorstatus is tijdelijk niet beschikbaar.') } }
  useEffect(() => { void search(); void loadDlt(); void loadGenerator() }, [])
  const submit = async (event: FormEvent) => { event.preventDefault(); if (!form.reportId.trim() || !form.category) { setFormError('Vul reportId en categorie in.'); return }; setFormError(''); try { await publishReport({ ...form, reportId: form.reportId.trim() }); setForm({ reportId: '', category: '', district: '' }) } catch { setFormError('De melding kon niet veilig worden verzonden.') } }
  const action = async (name: 'start' | 'stop' | 'generate-one') => { setGeneratorLoading(true); setGeneratorError(''); try { const response = await generatorAction(name); if ('running' in response) setGenerator(response); else await loadGenerator() } catch { setGeneratorError('Generatoractie is niet beschikbaar.') } finally { setGeneratorLoading(false) } }
  return <main className="shell"><header><p className="eyebrow">Openbare ruimte · Nederland</p><h1>CivicSignal NL</h1><p>Meldingen worden via Kafka verwerkt en daarna door Elasticsearch doorzoekbaar.</p></header>
    <section className="panel"><h2>Nieuwe melding</h2><form onSubmit={submit}><label>Report-ID<input aria-label="Report-ID" value={form.reportId} onChange={e => setForm({ ...form, reportId: e.target.value })} /></label><label>Categorie<select aria-label="Publicatiecategorie" value={form.category} onChange={e => setForm({ ...form, category: e.target.value })}><option value="">Kies een categorie</option>{categories.map(c => <option key={c}>{c}</option>)}</select></label><label>Stadsdeel<input value={form.district} onChange={e => setForm({ ...form, district: e.target.value })} /></label><button>Melding publiceren</button></form>{formError && <p role="alert" className="alert error">{formError}</p>}</section>
    <section className="panel"><div className="section-heading"><div><h2>Demo-databron</h2><p className="synthetic-warning">Dit is synthetische demonstratiedata en bevat geen echte burgermeldingen.</p></div><button className="secondary" onClick={() => void loadGenerator()}>Vernieuwen</button></div>{generatorError ? <p className="alert error" role="alert">{generatorError}</p> : generator && <><p>Status: {generator.running ? 'actief' : 'gestopt'} · {generator.generatedThisRun}/{generator.maximumPerRun} · interval {generator.interval} · laatste generatie {date(generator.lastGeneratedAt)}</p><div className="actions"><button disabled={!generator.enabledByConfiguration || generatorLoading} onClick={() => void action('start')}>Starten</button><button disabled={!generator.enabledByConfiguration || generatorLoading} onClick={() => void action('stop')}>Stoppen</button><button disabled={!generator.enabledByConfiguration || generatorLoading} onClick={() => void action('generate-one')}>Eén melding genereren</button></div>{!generator.enabledByConfiguration && <p className="empty">Generator is uitgeschakeld via configuratie.</p>}</>}</section>
    <section className="panel"><h2>Meldingen zoeken</h2><form className="filters" onSubmit={e => { e.preventDefault(); void search() }}><label>Vrije tekst<input value={filters.q} onChange={e => setFilters({ ...filters, q: e.target.value })} /></label><label>Categorie<select value={filters.category} onChange={e => setFilters({ ...filters, category: e.target.value })}><option value="">Alle categorieën</option>{categories.map(c => <option key={c}>{c}</option>)}</select></label><label>Stadsdeel<input value={filters.district} onChange={e => setFilters({ ...filters, district: e.target.value })} /></label><label>Bron<select aria-label="Bron" value={filters.sourceType} onChange={e => setFilters({ ...filters, sourceType: e.target.value })}><option value="">Alle bronnen</option><option value="MANUAL">Handmatig</option><option value="SYNTHETIC">Synthetisch</option></select></label><button>Zoeken</button></form>{loading ? <p>Zoeken laden…</p> : searchError ? <p role="alert" className="alert error">{searchError}</p> : results.items.length === 0 ? <p className="empty">Geen meldingen gevonden met deze filters.</p> : <div className="cards">{results.items.map(item => <article key={item.reportId}><h3>{item.reportId} <span className="source-badge">{item.sourceType === 'SYNTHETIC' ? 'Synthetisch' : 'Handmatig'}</span></h3><p>{item.category} · {item.district || '—'}</p><small>{date(item.occurredAt)} · {item.sourceName}</small></article>)}</div>}</section>
    <section className="panel"><div className="section-heading"><div><h2>Niet-verwerkte meldingen</h2><p>Lokale demonstratiefunctie: tijdelijk, zonder polling of replay.</p></div><button className="secondary" onClick={() => void loadDlt()}>Vernieuwen</button></div>{dltLoading ? <p>Niet-verwerkte meldingen laden…</p> : dltError ? <p role="alert" className="alert error">{dltError}</p> : dlt.items.length === 0 ? <p className="empty">Geen niet-verwerkte meldingen.</p> : <div className="dead-letter-list">{dlt.items.map(item => <article key={`${item.originalTopic}-${item.originalPartition}-${item.originalOffset}`}><h3>{item.failureType}</h3><p>{item.failureMessage.slice(0, 180)}</p><small>{date(item.failedAt)} · key/reportId: {item.originalKey || '—'}</small></article>)}</div>}</section>
  </main>
}
