import { useState, type FormEvent } from 'react'
import { publishReport } from './api'
import { categories } from './FilterBar'

export function SourcesPage() {
  const [form, setForm] = useState({ reportId: '', category: '', district: '' }); const [message, setMessage] = useState(''); const [failed, setFailed] = useState(false)
  const submit = async (event: FormEvent) => { event.preventDefault(); if (!form.reportId.trim() || !form.category) { setFailed(true); setMessage('Vul een report-ID en categorie in.'); return } setMessage(''); try { await publishReport({ ...form, reportId: form.reportId.trim() }); setForm({ reportId: '', category: '', district: '' }); setFailed(false); setMessage('De melding is veilig aangeboden aan Kafka.') } catch { setFailed(true); setMessage('De melding kon niet veilig worden verzonden.') } }
  return <section aria-labelledby="sources-title"><p className="eyebrow">Herkomst en betekenis</p><h2 id="sources-title">Databronnen</h2><div className="source-grid">
    <article className="panel source-card"><span className="source-badge source-manual">Handmatig</span><h3>Gebruikersinvoer</h3><p>Een lokale gebruiker voert zelf een report-ID, categorie en optioneel stadsdeel in. Ontbrekende velden blijven onbekend.</p><form className="manual-form" onSubmit={submit}><label>Report-ID<input aria-label="Report-ID" value={form.reportId} onChange={event => setForm({ ...form, reportId: event.target.value })}/></label><label>Categorie<select aria-label="Publicatiecategorie" value={form.category} onChange={event => setForm({ ...form, category: event.target.value })}><option value="">Kies een categorie</option>{categories.map(item => <option key={item}>{item}</option>)}</select></label><label>Stadsdeel<input value={form.district} onChange={event => setForm({ ...form, district: event.target.value })}/></label><button>Publiceer melding</button></form>{message && <p role={failed ? 'alert' : 'status'} className={`alert ${failed ? 'error' : 'success'}`}>{message}</p>}</article>
    <article className="panel source-card"><span className="source-badge source-synthetic">Synthetisch</span><h3>Demonstratiedata</h3><p>Gecontroleerde fictieve meldingen voor ontwikkeling en portfolio-demonstraties. Ze zijn nooit officiële brondata en mogen niet als werkelijk incident worden geïnterpreteerd.</p><p>Generatorbediening is uitsluitend zichtbaar na beheerlogin.</p></article>
    <article className="panel source-card"><span className="source-badge source-official_open_data">Officiële open data</span><h3>Gemeente Amsterdam Open Data</h3><p>Een openbare subset van Meldingen Openbare Ruimte. Niet alle Amsterdamse meldingen zijn opgenomen en historische brondefinities kunnen wijzigen.</p><p>Alleen veilige classificatie-, tijd-, status- en afgeronde visualisatievelden worden verwerkt; vrije tekst en persoonsgegevens niet.</p><a href="https://api.data.amsterdam.nl/v1/docs/datasets/meldingen.html" target="_blank" rel="noreferrer">Officiële documentatie</a><p><small>Creative Commons Naamsvermelding; vermeld Gemeente Amsterdam bij hergebruik.</small></p></article>
  </div><section className="panel"><h3>Privacy- en kwaliteitskeuzes</h3><ul><li>Geen adressen, meldergegevens of volledige bronpayload in het dashboard.</li><li>Locaties zijn uitsluitend openbare visualisatiecoördinaten en kunnen afgerond zijn.</li><li>Ongeldige of ontbrekende coördinaten verschijnen niet op de kaart.</li><li>Bronpanelen met beheeracties mounten pas na succesvolle login.</li></ul></section></section>
}
